version: '3.9'

services:
  web:
    container_name: tms_django_app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: [ "/app/docker-entrypoint.sh" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tms-network

  db:
    container_name: db-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tms-network

volumes:
  postgres_data:

networks:
  tms-network:
